spring:
  datasource:
    url: ${DB_URL}       # A nuvem vai preencher isto
    username: ${DB_USER} # A nuvem vai preencher isto
    password: ${DB_PASS} # A nuvem vai preencher isto
  jpa:
    hibernate:
      ddl-auto: update # Cria as tabelas automaticamente